name: get_annotation
description: Get Ensembl gene annotation
keywords:
  - Ensembl
  - annotation
tools:
  - get_ensembl_gene_annotation.pl:
      description: |
        Perl script to download gene annotation data using the Ensembl Perl API
      homepage: https://github.com/iansealy/bio-misc
      documentation: https://github.com/iansealy/bio-misc
      licence: ["GPL3"]
input:
  - species:
    type: value
    description: |
      Name of species to get annotation for (genus_species)
      e.g. danio_rerio
  - ensemblVersion:
    type: value
    description: Ensembl version number
output:
  - out_file:
    type: file
    description: annotation file
authors:
  - "@richysix"
maintainers:
  - "@richysix"
